### ISSUE TITLE
Cannot import name 'monitor_manager'

### ISSUE THREAD

**Issue by malagori** [shaneshixiang/rllabplusplus#1]
Hi,

I successfully installed rllabplusplus, and the trpo_cartpole.py example worked fine, but I'm getting an error with algo_gym_stub.py

python algo_gym_stub.py --exp=HalfCheetah-v1
Traceback (most recent call last):
  File "algo_gym_stub.py", line 1, in <module>
    from sandbox.rocky.tf.launchers.launcher_utils import FLAGS, get_env_info, get_annotations_string
  File "/home/RL-work/code/rllab/rllabplusplus/sandbox/rocky/tf/launchers/launcher_utils.py", line 10, in <module>
    from rllab.envs.gym_env import GymEnv
  File "/home/RL-work/code/rllab/rllabplusplus/rllab/envs/gym_env.py", line 5, in <module>
    from gym.monitoring import monitor_manager
ImportError: cannot import name 'monitor_manager'

Do you know how to fix this problem?

**Comment by tigerneil** [comment]
check this: https://github.com/openai/rllab/issues/67

**Comment by malagori** [comment]
@tigerneil : Thanks!
I think, the problem is still open or may be I missed something? Did you get it running?

**Comment by rlbayes** [comment]
I have it fixed on new version (merged from openai/rllab), but I am cleaning up the new codes (added new features) and have not committed. For now, you may install older gym versions. If I recall correctly, gym==5.6 for example works. Issues with monitor are also described here: https://pypi.python.org/pypi/gym.

**Comment by alexpashevich** [comment]
Replacing rllabplusplus/rllab/envs/gym_env.py by the original file from openai/rllab works for sure however I did not try downgrading to older gym yet.

**Comment by malagori** [comment]
@shaneshixiang and @alexpashevich :
I replaced gym_env.py from openai/rllab and installed gym==5.6 but it didn't work. However,
with gym==8.0 it works now.
Thanks a lot :)
